//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeAutomation_v3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kasa
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int TableId { get; set; }
        public int SalesId { get; set; }
        public System.DateTime OrderTime { get; set; }
        public int Count { get; set; }
        public decimal Sum { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Sales Sales { get; set; }
        public virtual Table Table { get; set; }
    }
}
